import os
from dash import Dash, html, callback
from dash.dependencies import Input, Output
from data_store import dropdown_options, df
from utils.summary_parser import parse_summary

# this callback updates the executive summary text based on the selected firm
# it loads summaries that are generated by GPT API and stored in ./data/executive_summaries/{firm}/2025.txt

@callback(
    Output("summary-text", "children"),
    Input("firm-selector", "value")
)
def load_summary(firm):

    if firm is None:
        return "Select a firm to view the AI summary."

    filepath = f"./data/executive_summaries/{firm}/2025.txt"

    if not os.path.exists(filepath):
        return f"No summary available for {firm}."

    with open(filepath, "r", encoding="utf-8") as f:
        text = f.read()

    #remove first line if it doesn't have a period
    if "." not in text.split("\n")[0]:
        text = "\n".join(text.split("\n")[1:])


    #remove any initial whitespace on first line
    text = text.lstrip()

    #add indents to each paragraph
    paragraphs = [p.strip() for p in text.split("\n\n") if p.strip()]

    paragraphs = ["   " + p for p in paragraphs]

    text = "\n\n".join(paragraphs)



    return text
    
