
from dash import html

# this is the layout for the executive summary page

def page3_layout():
    return html.Div(style={'fontFamily': 'Inter, sans-serif'}, children=[
    
    html.Div(
        html.H2(
            "Executive Risk Summary - 2025", 
            style={
                'fontFamily': 'Inter, sans-serif',
                'textAlign': 'center',
                'margin': '0',       
                'color': '#242c34'
            }
        ),
        style={
            #
            'backgroundColor': '#f0f4f8',
            'padding': '20px',           
            'borderRadius': '10px',      
            'border': '1px solid #d1d9e0', 
            'boxShadow': '2px 2px 5px rgba(0,0,0,0.05)', 
            'marginBottom': '20px'       
        }
    ),     

    #summary-text is what we fetch from the callback and contains the executive summary generated by GPT

    html.Div(
        id="summary-text",
        style={
            "whiteSpace": "pre-wrap",
            "lineHeight": "1.6",
            "marginTop": "20px",
            "padding": "10px",
            "border": "1px solid #ddd",
            'backgroundColor': '#f9f9f9',
            'color': '#333333',
            'maxWidth': '800px',
            'margin': '0 auto'
            
        }
    )
])
